disable signature of test pypi (#585)
*Issue #, if available:*
github release-build workflow step Publish to PyPI error:
```
Checking dist-pypi/aws_opentelemetry_distro-0.14.2-py3-none-any.whl: PASSED
Checking dist-pypi/aws_opentelemetry_distro-0.14.2.tar.gz: PASSED
Notice: Generating and uploading digital attestations
Error: Attestation generation failure: The following distributions already have publish attestations: * /github/workspace/dist-pypi/aws_opentelemetry_distro-0.14.2.tar.gz -> /github/workspace/dist-pypi/aws_opentelemetry_distro-0.14.2.tar.gz.publish.attestation
```

*Description of changes:*
The issue might be cased by running github action
`pypa/gh-action-pypi-publish` twice, the first one is publishing to Test
PyPI with signature, then the second one for prod PyPI will see
attestation file exists.

The fix is by disabling signature of the Test PyPI since it is not
required.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.