refactor(pr-build): split tox test into per-framework isolated envs  (#703)
*Description of changes:*

The single shared tox environment installed all framework dependencies
for each instrumentation tests into one virtual environment. This caused
several problems:

- Dependency conflicts: frameworks pull in conflicting transitive
dependencies, making the environment fragile and order-dependent which
means that a broken dependency in one framework could blocketests for
all frameworks

- Python has to resolve multiple dependency paths for each instrumented
library which can get VERY large, see:
https://pip.pypa.io/en/stable/topics/dependency-resolution/#dependency-resolution
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.

error: resolution-too-deep

× Dependency resolution exceeded maximum depth
╰─> Pip cannot resolve the current dependencies as the dependency graph is too complex for pip to solve efficiently.

hint: Try adding lower bounds to constrain your dependencies, for example: 'package>=2.0.0' instead of just 'package'.

Link: https://pip.pypa.io/en/stable/topics/dependency-resolution/#handling-resolution-too-deep-errors
```

- every test suite ran sequentially in one env, even though the
frameworks are completely independent

parities the same tox.ini setup as upstream:
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/tox.ini

TODO: we SHOULD create a followup PR and add 3.14 once
https://github.com/aws-observability/aws-otel-python-instrumentation/pull/701
is merged

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.