chore: remove Python 3.9 EKS E2E test (#756)
*Issue #, if available:*

*Description of changes:*
The urllib3 dependency release 2.7.0 requires Python 3.10+. Our python
EKS test builds the image from Python 3.11 and then fails when injected
into a Python 3.9 container with the following type error:

```
File "/otel-auto-instrumentation-python/urllib3/_base_connection.py", line 10, in <module>
    bytes, typing.IO[typing.Any], typing.Iterable[bytes | str], str
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

We will drop this test as Python 3.9 is EOL and upstream has already
dropped 3.8 support. We will officially drop Python 3.9 support ahead of
the next major/minor release.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.