pin urllib3 version in docker setup (#310)
*Issue #, if available:*
Attempt to pin urllib3 version to fix python 3.8 runtime issue.

```
Defaulted container "my-container" out of: my-container, opentelemetry-auto-instrumentation-python (init)
Error in sitecustomize; set PYTHONVERBOSE for traceback:
RuntimeError: Python 3.9 or later is required
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
.
.
.
 File "/usr/local/lib/python3.8/site-packages/botocore/compat.py", line 32, in <module>
    from urllib3 import exceptions
  File "/otel-auto-instrumentation-python/urllib3/__init__.py", line 14, in <module>
    from . import exceptions
  File "/otel-auto-instrumentation-python/urllib3/exceptions.py", line 26, in <module>
    _TYPE_REDUCE_RESULT = tuple[typing.Callable[..., object], tuple[object, ...]]
TypeError: 'type' object is not subscriptable
```

*Test plan:*
Tested locally on playground EKS cluster and validated the change fixes
the startup runtime issue. Will monitor EK2 workflow after PR is merged
to ensure it passes there as well.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.